server.port=8081
keycloak.auth-server-url=http://localhost:8080
keycloak.resources=auth-service-client
keycloak.public-client=true
keycloak.bearer-only=true
keycloak.realm=auth-service-realm
keycloak.client_id=auth-service-client
keycloak.client_secret=auth-service-client
keycloak.admin.username=admin
keycloak.admin.password=admin321
keycloak.use-resource-role-mappings=true
keycloak.user.username-attribute=username
keycloak.user.email-attribute=email
keycloak.user.email-verification=enabled
keycloak.user.password-attribute=password
keycloak.user.jwks-uri=http://localhost:8080/realms/auth-service-realm/protocol/openid-connect/certs
keycloak.logout-url=http://localhost:8080/realms/auth-service-realm/protocol/openid-connect/logout

spring.application.name=auth-service
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/auth-service-realm

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.instance.prefer-ip-address=true

#Zookeeper configuration
zookeeper.connect=localhost:2181
zookeeper.image=confluentinc/cp-zookeeper:7.5.0
container_name=zookeeper
environment=ZOOKEEPER_CLIENT_PORT: 2181
ZOOKEEPER_TICK_TIME=2000
ports=2181
# =========Kafka configuration=========
#spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.group-id=user-service-group
spring.kafka.producer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.consumer.group-id=user-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafak.properties.spring.json.trusted.packages="*"
spring.main.allow-bean-definition-overriding=true
#spring.main.lazy-initialization=true
#spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.username=postgresql
#spring.datasource.password=admin

